
-- ============================================================
-- 1. What is the total sales/revenue generated by the company?
-- ============================================================
select 
sum(p.price * od.quantity) as total_sales
from products p 
join order_details od
on od.product_id = p.product_id;

-- ============================================================
-- 2. What is the total profit generated by the company?
-- ============================================================
select sum(profit) as total_profit
from order_details ;

-- ============================================================
-- 3. How many orders has the company received?
-- ============================================================
select 
count(order_id) as total_orders
from orders;

-- ============================================================
-- 4. How many units of products have we sold in total?
-- ============================================================
select 
sum(quantity) as total_quantity_sold
from order_details;

-- ============================================================
-- 5.What is the average amount spent per order? 
-- ============================================================
select
sum(p.price * od.quantity) / count(distinct o.order_id)  as average_order_value
from products p
join order_details od 
on od.product_id = p.product_id
join orders o 
on o.order_id = od.order_id;

-- ============================================================
-- 6. How much sales revenue did each product category generate?
-- ============================================================
select p.category ,
sum(p.price * od.quantity) as total_sales
from products p 
join order_details od 
on p.product_id = od.product_id
group by p.category;

-- ============================================================
-- 7. How much total sales did each region generate?
-- ============================================================
select c.region ,
sum(p.price * od.quantity) as total_sales 
from customers c
join orders o 
on o.customer_id = c.customer_id 
join order_details od 
on od.order_id = o.order_id 
join products p 
on od.product_id = p.product_id
group by c.region;

-- ============================================================
-- 8. Which product generated the highest sales revenue?
-- ============================================================
select p.product_name ,
sum(p.price * od.quantity) as total_sales
from products p 
join order_details od 
on od.product_id = p.product_id
group by p.product_name
order by total_sales desc
limit 1;

-- ============================================================
-- 9. Give me the top 3 products by total sales revenue.
-- ============================================================
select p.product_name ,
sum(p.price * od.quantity) as total_sales
from products p 
join order_details od 
on od.product_id = p.product_id 
group by p.product_name
order by total_sales desc
limit 3;

-- ============================================================
-- 10. How much sales revenue did the company generate in each month?
-- ============================================================
select 
month(o.order_date) as month ,
sum(p.price * od.quantity) as total_sales
from products p 
join order_details od 
on od.product_id = p.product_id
join orders o 
on od.order_id = o.order_id
group by month(o.order_date)
order by month(o.order_date);

-- ============================================================
-- 11. How many orders were placed from each region?
-- ============================================================
select c.region ,
count(distinct o.order_id ) as total_orders
from customers c 
join orders o 
on o.customer_id = c.customer_id 
group by c.region;

-- ============================================================
-- 12. What is the average order value for each region?
-- ============================================================
select c.region ,
sum(p.price * od.quantity) / count(distinct o.order_id) as avg_order_value
from customers c 
join orders o 
on o.customer_id = c.customer_id 
join order_details od 
on od.order_id = o.order_id 
join products p 
on od.product_id = p.product_id 
group by c.region;

-- ============================================================
-- 13. Which product generated the highest total profit?
-- ============================================================
select p.product_name , 
sum(od.profit) as total_profit
from products p 
join order_details od 
on od.product_id = p.product_id 
group by p.product_name 
order by total_profit desc
limit 1;

-- ============================================================
-- 14. Which customers have placed more than one order?
-- ============================================================
select c.customer_name ,
count(o.order_id) as total_orders
from customers c 
join orders o 
on o.customer_id = c.customer_id 

group by c.customer_name 
having total_orders > 1;

-- ============================================================
-- 15. Which customer has spent the most money?
-- ============================================================
select c.customer_name ,
sum(p.price * od.quantity) as total_spent
from customers c 
join orders o 
on o.customer_id = c.customer_id 
join order_details od 
on od.order_id = o.order_id 
join products p 
on od.product_id = p.product_id 
group by c.customer_name 
order by total_spent desc
limit 1;

-- ============================================================
-- 16. Find all customers who have never placed an order.
-- ============================================================
select c.customer_name 
from customers c
left join orders o
on o.customer_id = c.customer_id
where o.order_id is null ;

-- ============================================================
-- 17. Which product category sold the highest number of units?
-- ============================================================
select p.category ,
sum(od.quantity) as total_quantity_sold
from products p 
join order_details od 
on od.product_id = p.product_id 
group by p.category
order by total_quantity_sold desc
limit 1;

-- ============================================================
-- 18. Which product category generated the highest total profit?
-- ============================================================
select p.category ,
sum(od.profit) as total_profit
from products p 
join order_details od 
on od.product_id = p.product_id 
group by p.category
order by total_profit desc
limit 1;

-- ============================================================
-- 19. What is the average age of customers in each region?
-- ============================================================
select region ,
avg(age) as average_age
from customers 
group by region;

-- ============================================================
-- 20. Which customer has placed the most orders?
-- ============================================================
select c.customer_name ,
count(o.order_id) as total_orders 
from customers c 
join orders o 
on o.customer_id = c.customer_id 
group by c.customer_name 
order by total_orders desc
limit 1;

-- ============================================================
-- 21. Which product was ordered most frequently?
-- ============================================================
select p.product_name , 
COUNT(distinct od.order_id) as times_orders
from products p 
join order_details od 
on od.product_id = p.product_id 
group by p.product_name
order by times_orders desc
limit 1;

-- ============================================================
-- 22. Which products have never been ordered?
-- ============================================================
select p.product_name 
from products p 
left join order_details  od 
on od.product_id = p.product_id 
where od.product_id is null;

-- ============================================================
-- 23 Which customer generated the highest total profit for the company?
-- ============================================================
select c.customer_name , 
sum(od.profit) as total_profit
from customers c
join orders o 
on o.customer_id = c.customer_id 
join order_details od 
on od.order_id = o.order_id 
group by c.customer_name 
order by total_profit desc
limit 1;

-- ============================================================
-- 24. What is the profit margin for each product category?
-- ============================================================
select p.category ,
sum(od.profit) / sum(p.price * od.quantity) * 100  as profit_margin
from products p 
join order_details od 
on od.product_id = p.product_id 
group by p.category ;

-- ============================================================
-- 25.How many customers have placed more than one order? 
-- ============================================================
select 
count(*) as repeat_customers
from (
select c.customer_id , c.customer_name ,
count(o.order_id) as total_orders
from customers c 
join orders o 
on o.customer_id = c.customer_id 
group by c.customer_id, c.customer_name 
having count(o.order_id) > 1
) as repeat_customers;

-- =============================================================================================
-- 26. Show the total sales for each month, and identify the month with the highest sales.
select -- ======================================================================================
month(o.order_date) as month,
sum(p.price * od.quantity) as total_sales 
from products p 
join order_details od 
on od.product_id = p.product_id 
join orders o 
on od.order_id = o.order_id
group by month(o.order_date)
order by total_sales desc;

-- ============================================================
-- 27. Which month generated the highest total profit?
-- ============================================================
select 
month(o.order_date) as month,
sum(od.profit) as total_profit
from orders o 
join order_details od 
on od.order_id = o.order_id 
group by month(o.order_date)
order by total_profit desc
limit 1;

-- ====================================================================================
-- 28. For each product category, show total sales, total profit, and profit margin.
-- =====================================================================================
select p.category ,
sum(p.price * od.quantity) as total_sales ,
sum(od.profit) as total_profit,
sum(od.profit) / sum(p.price * od.quantity) * 100 as profit_margin
from products p 
join order_details od 
on od.product_id = p.product_id 
group by p.category;

-- ==========================================================================================
-- 29. Find customers whose total spending is greater than the average customer spending.
-- ===========================================================================================
with customer_spending as 
(
select c.customer_id, c.customer_name ,
sum(p.price * od.quantity) as total_spent
from customers c
join orders o 
on o.customer_id = c.customer_id 
join order_details od 
on od.order_id = o.order_id
join products p 
on od.product_id = p.product_id 
group by c.customer_id, c.customer_name
) 
select 
customer_name , total_spent
from customer_spending 
where total_spent > 
(select avg(total_spent) from customer_spending 
);

-- ============================================================================================
-- 30. Who are the top 3 customers that generated the highest total profit for the company? 
-- ============================================================================================
select c.customer_name ,
sum(od.profit) as total_profit
from customers c 
join orders o 
on o.customer_id = c.customer_id 
join order_details od 
on od.order_id = o.order_id 
group by c.customer_name 
order by total_profit desc 
limit 3;

-- =========================================================================
-- 31. Find the customer who has the second-highest total spending.
-- ==========================================================================
select c.customer_name,
sum(p.price * od.quantity) as total_spend
from customers c 
join orders o 
on o.customer_id = c.customer_id
join order_details od 
on od.order_id = o.order_id 
join products p
on od.product_id = p.product_id
group by c.customer_name 
order by total_spend desc
limit 1 offset 1 ;

-- ====================================================================================
-- 32.What percentage of total company sales comes from each product category?
-- ====================================================================================
with category_sales as
(
select p.category ,
sum(p.price * od.quantity) as total_sales 
from products p 
join order_details od 
on od.product_id = p.product_id 
group by p.category
)
select 
category , total_sales,
total_sales / sum(total_sales) over() * 100 as total_percentage
from category_sales; 

-- ============================================================
-- 33. Which product category has the highest profit margin?
-- ============================================================
select p.category ,
sum(od.profit) / sum(p.price * od.quantity) * 100 as profit_margin
from products p
join order_details od
on od.product_id = p.product_id 
group by p.category
order by profit_margin desc
limit 1 ;

-- ==================================================================
-- 34. Which product generated the second-highest total profit?
-- ====================================================================
select p.product_name ,
sum(od.profit) as total_profit
from products p 
join order_details od 
on od.product_id = p.product_id 
group by p.product_name 
order by total_profit desc
limit 1 offset 1;

-- ============================================================
-- 35.Find customers who generated a total profit of 0 or less.
-- ============================================================ 
select c.customer_name , 
sum(od.profit) as total_profit
from customers c 
join orders o 
on o.customer_id = c.customer_id 
join order_details od 
on od.order_id = o.order_id 
group by c.customer_name 
having total_profit <= 0;

-- =================================================================================
-- 36. Find the product with the highest total sales within each category.
-- =================================================================================
with product_sales as
(
select  p.category ,p.product_name,
sum(p.price * od.quantity) as total_sales 
from products p 
join order_details od 
on od.product_id = p.product_id 
group by  p.product_name, p.category 
),
ranked_products as
(
select  *,
row_number() over(partition by category order by total_sales desc ) as rn
from product_sales
)
select *
from ranked_products
where rn = 1;

-- ============================================================
-- 37.Find the first order date for each customer. 
-- ============================================================
select c.customer_name , 
min(o.order_date) 
from customers c 
join orders o 
on o.customer_id = c.customer_id 
group by  c.customer_name;

-- ============================================================
-- 38.Find the latest order date for each customer.
-- ============================================================
select c.customer_name , 
max(o.order_date) as latest_order 
from customers c 
join orders o 
on o.customer_id = c.customer_id 
group by c.customer_name;


-- ==============================================================================
-- 39.Find customers who placed orders in more than one different month. 
-- ===============================================================================
select c.customer_name , 
count(distinct month(o.order_date)) as month
from customers c 
join orders o 
on o.customer_id = c.customer_id 
group by c.customer_name 
having count(distinct month(o.order_date)) > 1;

-- ===================================================================
-- 40. Find the product category that has the highest total sales 
--- among all categories whose profit margin is greater than 15%. 
--- Show the category, total sales, total profit, and profit margin.
-- =====================================================================
select p.category ,
sum(p.price * od.quantity) as total_sales ,
sum(od.profit) as total_profit ,
sum(od.profit) / sum(p.price * od.quantity) * 100 as profit_margin
from products p 
join order_details od 
on od.product_id = p.product_id 
group by p.category
having sum(od.profit) / sum(p.price * od.quantity) * 100 > 15
order by total_sales desc 
limit 1 ;



































